### ISSUE TITLE
Program stops in between 

### ISSUE THREAD

**Issue by yash-61016** [yash-61016/PolicyManager#1]
**Expected:**
The program is supposed to run in a loop until the user has exited. Once an Option is fully completed it runs the loop again. So it asks you after every loop that what option you want to choose, one of them is exit and if you choose exit you exit. 
**Problem**
At the moment the program is working fine how its supposed to be but after option 1 it breaks and gives one error "Exception in thread "main" java.util.NoSuchElementException". After every other option its running loop fine, but just after the user has completed option 1, it asks user to choose option and stops.
<img width="646" alt="Screenshot 2021-01-30 at 16 54 38" src="https://user-images.githubusercontent.com/73232849/106362638-da242200-631b-11eb-8e47-7a2acbf63da1.png">

**Comment by ishailendra** [comment]
Linked a pull request that will close this issue.

[NoSuchElementException fix #2](https://github.com/yash-61016/PolicyManager/pull/2)
